name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
					cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - run: yarn install --frozen-lockfile

      - run: yarn build
				env:
					TURBO_TOKEN: 0EE28UmWOtlFBZiXxR2t2lC2
					TURBO_TEAM: rafaeld3v

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: touch storybook-static/.nojekyll && yarn run deploy-storybook -- --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}